mysite/urls.py
from django.conf.urls.defaults import *
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView
from django.contrib import admin
from mysite.nature.models import *
from mysite.nature.views import *

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('mysite.nature.urls')),
)

mysite/naturelogs/models.py
from django.db import models
from django.core.urlresolvers import reverse
import datetime
from django.contrib.auth.models import User
import os
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, Adjust
import tagging
from tagging.fields import TagField
from tagging.models import Tag

# *********************************************************************** #
# **************************set up/meta data **************************** #
# *********************************************************************** #

#where the different types of organisms (Bird, Tree, Amphibian) are stored
class OrganismType(models.Model):
	description = models.CharField(max_length=200)
	def __unicode__(self):
		return self.description
	def get_absolute_url(self):
		return "/type/%i/" % self.id 	

class TypeTag(models.Model):
	tag = models.ForeignKey(Tag)
	type = models.ForeignKey(OrganismType)

class IdentificationField(models.Model):
	type = models.ForeignKey(OrganismType, related_name="id_fields")
	name = models.CharField(max_length=200)

	def __unicode__(self):
		return self.name

class Family(models.Model):
	family_name = models.CharField(max_length=200)
	family_descr = models.CharField(max_length=200)
	def __unicode__(self):
		return self.family_name
	def __unicode__(self):
		return self.family_descr	
	class Meta:
		verbose_name_plural = "families"

class Order(models.Model):
	order_name = models.CharField(max_length=200)
	order_descr = models.CharField(max_length=200)
	def __unicode__(self):
		return self.order_name
	def __unicode__(self):
		return self.order_descr

class Sp_Class(models.Model):
	sp_class_name = models.CharField(max_length=200)
	sp_class_descr = models.CharField(max_length=200)
	def __unicode__(self):
		return self.sp_class_name
	def __unicode__(self):
		return self.sp_class_descr
	class Meta:
		verbose_name = "class"
		verbose_name_plural = "classes"	

class Phylum(models.Model):
	phylum_name = models.CharField(max_length=200)
	phylum_descr = models.CharField(max_length=200)
	def __unicode__(self):
		return self.phylum_name
	def __unicode__(self):
		return self.phylum_descr

class Kingdom(models.Model):
	kingdom_name = models.CharField(max_length=200)
	kingdom_descr = models.CharField(max_length=200)
	def __unicode__(self):
		return self.kingdom_name
	def __unicode__(self):
		return self.kingdom_descr

class PopulationStatus(models.Model):
	status_descr = models.CharField(max_length=200)
	def __unicode__(self):
		return self.status_descr
	class Meta:
		verbose_name_plural = "population statuses"	

class StateStatus(models.Model):
	status_descr = models.CharField(max_length=200)
	def __unicode__(self):
		return self.status_descr
	class Meta:
		verbose_name_plural = "state statuses"

class Region(models.Model):
	region_name = models.CharField(max_length=200)
	def __unicode__(self):
		return self.region_name

class State(models.Model):
	state = models.CharField(max_length=50)
	def __unicode__(self):
		return self.state

class ZipCode(models.Model):
	zipcode = models.CharField(max_length=5)
	latitude = models.DecimalField(max_digits=15, decimal_places=9)
	longitude = models.DecimalField(max_digits=15, decimal_places=9)
	state = models.ForeignKey(State, related_name="state_zip")
	county = models.CharField(max_length=100)
	country = models.CharField(max_length=100)
	def __unicode__(self):
		return self.county
	def __unicode__(self):
		return self.country
	def __unicode__(self):
		return self.zipcode	

# ****************************************************************** #
# ********************* organism/detail data *********************** #
# ****************************************************************** #

class Organism(models.Model):
	common_name = models.CharField(max_length=200)
	latin_name = models.CharField(max_length=200)
	population_status = models.ForeignKey(PopulationStatus, related_name="org_pop_status", null=True, default=None, blank=True)
	family = models.ForeignKey(Family, related_name="org_family", null=True, default=None, blank=True)
	order = models.ForeignKey(Order, related_name="org_order", null=True, default=None, blank=True)
	sp_class = models.ForeignKey(Sp_Class, related_name="org_class", null=True, default=None, blank=True)
	phylum = models.ForeignKey(Phylum, related_name="org_phylum", null=True, default=None, blank=True)
	kingdom = models.ForeignKey(Kingdom, related_name="org_kingdom", null=True, default=None, blank=True)
	type = models.ForeignKey(OrganismType, related_name="organisms")
	#ident_tips = models.TextField('identification tips', blank=True) no longer needed
	#habitat_descr = models.TextField('habitat description', blank=True) no longer needed
	#image = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True) no longer needed

	def get_absolute_url(self):
		return "/organism/%i/" % self.id 
	def get_edit_url(self):
		return	"/edit/organism/%i/" % self.id 
	def get_map_url(self):
		return "/map/organism/%i/" % self.id
	def get_add_ident(self):
		return "/add/organism/ident/%i/" % self.id
	def get_edit_ident(self):
		return "/edit/organism/ident/%i/" % self.id

	def __unicode__(self):
		return u"%s (%s)" % (self.common_name, self.latin_name)

	def save(self, *args, **kwargs):
		# Ensures the latin_name is always "Singleupcase otherslowercase"
		self.latin_name = self.latin_name[0].upper() + self.latin_name[1:].lower()
		return super(Organism, self).save(*args, **kwargs)
	class Meta:
		ordering=["common_name"]	

#stores the large, moderated text field users edit for helping with identification
class OrgIdentification(models.Model):
	organism = models.ForeignKey(Organism, related_name='org_ident', unique=True)
	identification = models.TextField(blank=True)
	#may want to add "last edit date, last edit user, etc"?
	def get_absolute_url(self):
		return "/organism/%i/" % self.organism.id
	def __unicode__(self):
		return self.identification


#stores the updated/created values for OrgIdentifications under review and the history
class OrgIdentificationReview(models.Model):
	STATUS_CHOICES = (
        (1, 'Approved'),
        (2, 'Pending'),
        (3, 'Rejected'),
    )
	organism = models.ForeignKey(Organism)
	identification = models.TextField(blank=True)
	modified_by = models.ForeignKey(User, related_name='+')
	modified_date = models.DateTimeField()
	status = models.IntegerField(choices=STATUS_CHOICES) #1 - Approved; 2 - Pending; 3 - Rejected
	reason = models.TextField(blank=True)
	moderated_by = models.ForeignKey(User, related_name='+', null=True, default=None, blank=True)
	moderated_date = models.DateTimeField(null=True, default=None, blank=True)
	def __unicode__(self):
		return self.identification
	def __unicode__(self):
		return self.reason


#store the identification fields for that organism (i.e. a leaf type)
class IdentificationDetail(models.Model):
	organism = models.ForeignKey(Organism, related_name="id_details")
	field = models.ForeignKey(IdentificationField, related_name="id_field_details")
	description = models.CharField(max_length=250) #Don't need this anymore
	def __unicode__(self):
		return u"%s is %s" % (self.field.name, self.description)
	#consider doing a def save here to store the description slugified...
	class Meta:
		verbose_name_plural = "identification details"

tagging.register(Organism)

class Location(models.Model):
	name = models.CharField(max_length=100)
	description = models.TextField(blank=True)
	latitude = models.DecimalField(max_digits=11, decimal_places=9)
	longitude = models.DecimalField(max_digits=11, decimal_places=9)
	miles_wide = models.DecimalField(max_digits=7, decimal_places=2)
	miles_tall = models.DecimalField(max_digits=7, decimal_places=2)
	created_by = models.ForeignKey(User, related_name="+")
	private = models.BooleanField()
	def __unicode__(self):
		return self.description
	def __unicode__(self):
		return self.name

	def get_absolute_url(self):
		return "/location/%i/" % self.id
	def get_edit_url(self):
		return "/edit/location/%i/" % self.id
	def get_map_url(self):
		return "/map/location/%i/" % self.id

#need to add a model/way to subscribe or follow other people's locations

#store the regions where an organism can be found
class OrgRegion(models.Model):
	organism = models.ForeignKey(Organism, related_name="org_regions")
	region = models.ForeignKey(Region, related_name="region_details")
	class Meta:
		verbose_name = "organism region"

#stores the endangered status of an organism for a particular state
class OrgStateStatus(models.Model):	
	organism = models.ForeignKey(Organism, related_name="org_states")
	state = models.ForeignKey(State, related_name="state_details")
	state_status = models.ForeignKey(StateStatus, related_name="state_status_details")
	class Meta:
		verbose_name = "organism state status"
		verbose_name_plural = "organism state statuses"

#stores the observation details for an observation event
class Observation(models.Model):
	organism = models.ForeignKey(Organism)
	user = models.ForeignKey(User, related_name="+")
	observation_date = models.DateTimeField()
	temperature = models.DecimalField(max_digits=5, decimal_places=2)
	latitude = models.DecimalField(max_digits=11, decimal_places=9)
	longitude = models.DecimalField(max_digits=11, decimal_places=9)
	location_descr = models.CharField('description of location', max_length=200)
	comments = models.CharField(max_length=200)
	quantity = models.IntegerField()
	observation_image = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
	parent_observation = models.ForeignKey('self', blank=True, default=None, null=True, help_text='The first observation of a static organism', related_name='child_observation')
	thumbnail = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1), ResizeToFill(50, 50)], image_field='observation_image', format='JPEG', options={'quality': 90})
	large_image = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1), ResizeToFill(500, 400)], image_field='observation_image', format='JPEG', options={'quality': 90})

mysite/templates/nature/base_about.html
{% extends "nature/base.html" %}
{% block title %}About SpeSee{% endblock title %}
{% block content %}
<h3>What is SpeSee?</h3>
	<p>At its core, there are 2 goals of SpeSee:</p>
	<h4>To create a user edited field guide</h4>
		<p>There are numerous places on the web that have excellent, detailed information on identifying various different kinds of organisms. However, I have always found these sites to be either difficult to use, or too hard to understand for the "backyard naturalist". So, if everything goes as planned, SpeSee will be a place that users can go to in order to find practical, straightforward information on how to identifying whatever it was they just saw, be it a bird, tree, mammal, reptile, or amphibian. Furthermore, as users develop their own tips on identifying those similar species, they can add them to the site.
	<h4>To facilitate the tracking of user organism observations</h4>
		<p>Again, while there may be some other sites that can facilitate "life lists", I haven't found any with the functionality of SpeSee, nor ones that tie directly into the field guide aspect of the site. Hopefully you will find creating lists, tracking observations, and sharing your lists with others to be a fun and useful experience.</p>
<h3>How do I use it?</h3>
	<p>For a great primer on how to use the site, see the blog posts on <a href="http://spesee.org/blog/categories/using-spesee/">using SpeSee</a> or any of the following post:</p>
	<ul class="unstyled">
		<li><a href="">Post about editing identifications info here (coming soon).</a></li>
		<li><a href="http://spesee.org/blog/2013/01/23/entering-observations/">Entering observations</a></li>
		<li><a href="">Post about creating lists/groups here (coming soon).</a></li>
	</ul>
{% endblock content %}
{% block right-content %}
    <div class="span10 offset1">
    	{% include "nature/include_contact.html" %}
    </div>
{% endblock right-content %}

mysite/templates/nature/base_course_update.html
{% extends "nature/base.html" %}
{% block app.css %}
<link rel="stylesheet" href="{{ STATIC_URL }}nature/css/colorbox/colorbox.css">
{% endblock %}
{% block title %}Edit Your List {% endblock title %}
{% block app.scripts %}
<script type="text/javascript" src="{{ MEDIA_URL }}js/colorbox/jquery.colorbox-min.js"></script>
<script type ="text/javascript">
function deleteItem(item_id){
  $.ajax({
      type: "GET",
      url: "/delete/list/item/"+ item_id +"/",
      success: function(){
            $("." + item_id).remove();
          }
      });
  }
function addItem(course, organism, common_name){
  $.ajax({
    type: "GET",
    url: "/add/list/" + course + "/item/" + organism + "/",
    success: function(data){
      var new_item_id = data;
      var htmlData = "<tr class='" + new_item_id + "'><td>" + common_name + "</td><td><a href='#' class='btn btn-danger btn-mini note'><i id='" + new_item_id + "' class='delete icon-remove icon-white'></i></a></td></tr>";
      $('#org_table').append(htmlData);
      //empty the selector field and focus on it
      $('#selector').val('');
      $('#selector').focus();
      //stops the form from refreshing the page like it normally would.
    }
  });
}
$(function() {
  {% if not course.is_group %}
  $("#id_group").parent().parent().hide();
  $("#current_group").hide();
  $("#add_group").hide();
  {% endif %}
  $("#selector").autocomplete({
      source: "{% url 'autocomplete' %}?search=organism",
      minLength: 3,
      select: function(event, ui) {
        $('#organism_id').val(ui.item.id);
        $('#common_name').val(ui.item.label);
      }
    });

  $("#org_table").on("click", ".delete", function(event){ 
    var item_id = event.target.id;
    deleteItem(item_id);
  });

  $("#add_organism").click(function(e){ 
    //get the autocomplete values for use below
    var organism_id = $('#organism_id').val();
    var common_name = $('#common_name').val();
    var course_id = $('#course_id').val();
    addItem(course_id, organism_id, common_name);    
    e.preventDefault();
  }); 
  $("#id_is_group").change(function(e){
    if (this.checked) {
      $("#id_group").parent().parent().show();
      $("#add_group").show();
    }
    else {
      $("#id_group").parent().parent().hide();
      $("#add_group").hide();
    }
  });
  $(".ajax").colorbox({height:"650px", width:"565px", iframe:true, onClosed:function(){window.location.reload();}});
  $('.note').tooltip({ title: 'Remove this organism', placement: 'right' });
});
</script>
{% endblock %}

{% block content %}
  {% if course.user.id == user.id %} 
    {% if perms.nature.add_course %}
        <h3>Edit your custom list</h3><a href="{{ course.get_absolute_url }}">Back to the list</a>
        <form action="" method="post" class="form-horizontal">
          <div class="form-row">
            {{ form.title.label_tag }}
            {{ form.title }}
            {{ form.title.errors }}
          </div>
        <table class="table">
          {{ form.as_table }}
           <tr id="current_group">
            <th><label for "current_group">Current Group:</label></th>
            <td><a href="{{ course.group.get_absolute_url }}{{ course.group|slugify }}">{{ course.group }}</a></td>
          </tr>
           <tr >
            <th><label for="id_group">Change Group:</label></th>
            <td>
              <select id="id_group" name="group">
                <option selected="selected" value"">---------</option>
                {% for group in group_list %}
                  <option value="{{ group.id }}">{{ group.name }}</option>
                {% endfor %}
              </select>
              <a id="add_group" class="ajax cboxElement btn" href="{% url 'group-add' %}">Create Group</a>
            </td>
          </tr>
          {% csrf_token %}
          <tr>
            <td><input type="submit" value="Update List Setup" class="submit btn" /></td>
          </tr>
        </table>
        </form>
        <form action="#" id="autocomplete_form" class="form-horizontal">
          <input type="text" id="selector" name="selector"/>
          <input type="hidden" id="organism_id" name="organism_id" />
          <input type="hidden" id="course_id" name="course_id" value="{{ course.id }}" />
          <input type="hidden" id="common_name" name="common_name" />
          <input type="submit" value="Add Organism" id="add_organism" class="btn" />
        </form>
        <table id="org_table" class="table">
            {% for x in detail_list %}
              <tr class="{{ x.id }}">
                <td>{{ x.organism }}</td>
                <td><a href="#" class="btn btn-danger btn-mini note"><i id="{{ x.id }}" class="delete icon-remove icon-white"></i></a></td>
              </tr>
            {% endfor %}
        </table>
      {% else %}
        <p>I'm sorry, you are not authorized to update this list. Please contact the administrator for more information.</p>
      {% endif %}
  {% else %}  
    <p>I'm sorry, you are not authorized to edit this list. Please contact the administrator for more information, or try a different list</p>
  {% endif %}
{% endblock %}

mysite/templates/nature/base_location_update.html
{% extends "nature/base.html" %}

{% block title %}Edit your Location{% endblock title %}
{% block app.scripts %}
<!-- Load TinyMCE -->
<script type="text/javascript" src="{{ MEDIA_URL }}js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
tinyMCE.init({
  mode: "textareas",
  theme: "simple"
});
</script>
<!-- /TinyMCE -->
{% endblock %}

{% block content %}
  {% if location.created_by.id == user.id %} 
    {% if perms.nature.add_location %}
    <form action="" method="post">
      {% csrf_token %}
     <table>
       {% for field in form %}
       <tr>
         <th>{{ field.label_tag }} {% if field.field.required %}<span class="requ">*</span>{% endif %}</th>
         <td>{{ field.errors }}{{ field }}
           {% if field.help_text %}
           <p class="help_text">{{ field.help_text }}</p>
           {% endif %}
         </td>
       </tr>
       {% endfor %}
       <tr><th></th><td><input type="submit" class="btn" value="Submit"></td></tr>
     </table>
    </form>
    {% else %}
      <p>sorry, no permissions</p>
    {% endif %}
  {% else %}
    <p>I'm sorry, you are not authorized to edit this observation. Please contact the administrator for more information, or try a different observation.</p>
  {% endif %}
{% endblock content %}
{% block right-content %}
{% if location.created_by.id == user.id %} 
  <div class="span10 offset1">
    <p class="alert alert-info">Click where you would like to center this location.</p>
  </div>
  <div id="map_canvas" class="span11" ></div>
  {% include 'nature/include_lookup_map.html' %}
{% endif %}
{% endblock %}

mysite/templates/nature/base_logged_out.html
{% extends "nature/base.html" %}

{% block content %}

<p>Thanks for spending some quality time with the Web site today.</p>

{% endblock %}

mysite/templates/nature/base_noresults.html
{% extends "nature/base.html" %}
{% block content %}
<p class="alert alert-error">It appears you didn't enter a valid value. Please return to the previous page and try again. If you continue to receive this message, please <a href="/contact/">contact us</a>.</p>
{% endblock %}

mysite/templates/nature/base_review_list.html
{% extends "nature/base.html" %}
{% block title %}Review Organism Changes{% endblock %}
{% block content %}
{% if perms.nature.add_orgidentificationreview %}
	{% if org_review_list %}
		<h2>Review Organism Changes:</h2>
		    <ul class="unstyled">
		    {% for org in org_review_list %}
		        <li><a href="{% url 'review-organism' org.id %}">{{ org.organism }}</a></li>
		    {% endfor %}
		    </ul>
	{% endif %}
	{% if image_review_list %}
		<h2>Review New Images:</h2>
		    <ul class="unstyled">
		    {% for image in image_review_list %}
		        <li><a href="{% url 'review-image' image.id %}">{{ image.review_image.organism }}</a></li>
		    {% endfor %}
		    </ul>
	{% endif %}
	{% if obs_review_list %}
		<h2>Review Unknown Observations:</h2>
		    <ul class="unstyled">
		    {% for obs in obs_review_list %}
		        <li><a href="{% url 'review-obs' obs.id %}">{{ obs.user}} - {{ obs.comments }}</a></li>
		    {% endfor %}
		    </ul>
	{% endif %}
	{% if not org_review_list and not image_review_list and not obs_review_list %}
		<p class="alert alert-info">There are no changes for review at this time!</p>
	{% endif %}
{% else %}
<p>I'm sorry, you are not authorized to moderate changes. Please contact the administrator for more information.</p>
{% endif %}
{% endblock content %}

mysite/templates/nature/base_search_tags.html
{% extends "nature/base.html" %}
{% block title %}Tag Search{% endblock title %}
{% block content %}
<h3>Tag search results:</h3>
{% if organism_list %}
<div class="media">
    {% for organism in organism_list %}
      {% if forloop.counter0|divisibleby:"3" %}<div class="row-fluid"><ul class="thumbnails">{% endif %}
        <li class="span4">
          <div class="thumbnail organism {{ organism.organism.type|lower }} well well-small">
          {% for images in organism.images_set.all %}
            {% if images.primary_image %}<img src="{{ images.wide_thumb.url }}" class="obs-image">{% endif %}
			{% empty %}<img src="holder.js/179x89" class= "obs-image">            	
          {% endfor %}
            <div class="caption">
              <h5>{{ organism.common_name }}</h5>
              <p><em>{{ organism.latin_name }}</em></p>
              <p><a class="btn btn-mini" href="{{ organism.get_absolute_url }}">View details »</a></p>
            </div>
          </div>
        </li>
      {% if forloop.last or forloop.counter|divisibleby:"3" %}</ul></div>{% endif %} 
    {% endfor %}
</div>
{% else %}
    <p>No organisms found.</p>
{% endif %}
{% endblock content %}
{% block app.scripts %}
<script src="{{ MEDIA_URL }}js/holder/holder.js"></script>
{% endblock %}

mysite/templates/nature/base_stats.html
{% extends "nature/base.html" %}
{% block title %}Stats{% endblock %}
{% block content %}
<h2>Global Stats:</h2>
{% if stats_list %}
    <ul class="large_list">
        <li>{{ stats_list.id__count }} Total Lists</li>
        {% if orgs_found %}
        <li>{{ orgs_found.total_found }} Organisms Found</li>
        {% endif %}
    </ul>
{% else %}
    <p>No Lists!</p>
{% endif %}
{% if user.is_authenticated %}
    <h2>My Stats:</h2>
    <p>Not set up yet.</p>
{% endif %}
{% endblock content %}

mysite/templates/nature/base_type.html
{% extends "nature/base.html" %}
{% block title %}Organism Types{% endblock %}
{% block content %}
<h1>Select an Organism Type below</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<!--the csrf_token prevents Cross Site Request Forgeries -->
{% for organismtype in type_list %}
    <p><a href="{{ organismtype.get_absolute_url }}">{{ organismtype.description }}</a></p>
{% endfor %}
{% endblock content %}

mysite/templates/nature/include_map.html
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB6b-LfSPC4oIvgGh2OyVvabLrgd9HSCRc&sensor=false"></script>
<script type="text/javascript">
var infowindow = null;
    $(document).ready(function () { initialize();  });

    function initialize() {

        var centerMap = new google.maps.LatLng(0, 0);

        var myOptions = {
            zoom: 4,
            center: centerMap,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        }

        var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

        setMarkers(map, sites);
	    infowindow = new google.maps.InfoWindow({
                content: "loading..."
            });
    }

    var sites = [
    {% if single_observation %}
    ['{{ single_observation.organism }}', {{ single_observation.latitude }}, {{ single_observation.longitude }}, 1, '{{ single_observation.organism}} <br>Seen {{ single_observation.observation_date }} by {{ single_observation.user }}', {% if not user.is_anonymous %}{% if user.id == single_observation.user.id %}'0066FF'{% else %}'009933'{% endif %}{% else %}'009933'{% endif %}]
    {% else %}
    {% for observation in map_observations %}
    ['{{ observation.organism }}', {{ observation.latitude }}, {{ observation.longitude }}, {{ forloop.counter }}, '{{ observation.organism}} <br>Seen {{ observation.observation_date }} by {{ observation.user }}', {% if not user.is_anonymous %}{% if user.id == observation.user.id %}'0066FF'{% else %}'009933'{% endif %}{% else %}'009933'{% endif %}]{% if not forloop.last %},{% endif %}
    {% endfor %}
    {% endif %}
];

    function setMarkers(map, markers) {
        var bounds = new google.maps.LatLngBounds();
        for (var i = 0; i < markers.length; i++) {
            var sites = markers[i];
            var pinImage = new google.maps.MarkerImage("http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=%E2%80%A2|" + sites[5]);
            var pinShadow = new google.maps.MarkerImage("http://chart.apis.google.com/chart?chst=d_map_pin_shadow",
                new google.maps.Size(40, 37),
                new google.maps.Point(0, 0),
                new google.maps.Point(12, 35));
            var siteLatLng = new google.maps.LatLng(sites[1], sites[2]);
            var marker = new google.maps.Marker({
                position: siteLatLng,
                map: map,
                icon: pinImage,
                shadow: pinShadow,
                title: sites[0],
                zIndex: sites[3],
                html: sites[4]
            });
            bounds.extend(siteLatLng);

            var contentString = "Some content";

            google.maps.event.addListener(marker, "click", function () {
                infowindow.setContent(this.html);
                infowindow.open(map, this);
            });
        }
        map.fitBounds(bounds);
    }
</script>

mysite/templates/nature/include_pagination.html
{% if is_paginated %}
	<div class="pagination pagination-centered">
		<ul>
			{% if page_obj.has_previous %}
				<li><a href="?page={{ page_obj.previous_page_number }}">«</a></li>
			{% else %}
				<li class="disabled"><a href="">«</a></li>
			{% endif %}
			{% for page_number in paginator.page_range %}
				{% ifequal page_number page_obj.number %}
					<li class="active"><a href="">{{ page_number }}</a></li>
				{% else %}
					<li><a href="?page={{ page_number }}">{{ page_number }}</a></li>
				{% endifequal %}
			{% endfor %}
			{% if page_obj.has_next %}
				<li><a href="?page={{ page_obj.next_page_number }}">»</a></li>
			{% else %}
				<li class="disabled"><a href="">»</a></li>
			{% endif %}
		</ul>
	</div>
{% endif %}

mysite/templates/nature/mapSpecies.html
<markers>
{% for observation in organism.observation_set.all %}
 <marker name="{{ organism.common_name }}" date= "{{ observation.observation_date }}" lat="{{ observation.latitude }}" lng="{{ observation.longitude }}" />
{% endfor %}
</markers>

mysite/templates/nature/search_ident_fields.html
{% extends "nature/base.html" %}
{% block title %}Advanced Search{% endblock title %}
{% block content %}
<h1>Identifying characteristic search results:</h1>
{% if organism_list %}
    <ul>
    {% for organism in organism_list %}
        <li><a href="{{ organism.get_absolute_url }}{{ organism.common_name|slugify }}">{{ organism.common_name }} ({{ organism.latin_name }})</a> </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No organisms are available.</p>
{% endif %}
{% endblock content %}

mysite/templates/nature/type.html
{% extends "nature/base.html" %}
{% block title %}Organism Types{% endblock %}
{% block content %}
<h1>{{ organismtype.description }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<h2>Identification Fields</h2>
{% for id_fields in organismtype.id_fields.all %}
<ul>
	<li>{{ id_fields.name }}</li>
</ul>
{% endfor %}
{% endblock content %}